[samsung-i9070] Add proper fix for framebuffer (#1106)
- Removed the framebuffer configuration in the initramfs hook
- Added patch for fixing the framebuffer mode in the kernel source
- Cleanup linux-samsung-i9070 APKBUILD

diff --git a/device/linux-samsung-i9070/APKBUILD b/device/linux-samsung-i9070/APKBUILD
--- a/device/linux-samsung-i9070/APKBUILD
+++ b/device/linux-samsung-i9070/APKBUILD
@@ -1,149 +1,113 @@
-# APKBUILD based on linux-vanilla aport. Changes:
-# - add findutils makedepend (necessary for the initramfs)
-# - it builds an initramfs - do not use ramdisk.cpio and
-#	ramdisk-recovery.cpio, in there, always use the
-#	initramfs from the kernel2 partition ("isorec")
-# - directly boot to that initramfs, not only when the recovery
-#	key combination was pressed.
-# - use Alpine's busybox-static instead of the pre-compiled
-#	binary, that comes with the source
-# - reduce lzo compression because Alpine's busybox doesn't
-#	support high compression
-# - add kernel modules installation
-# - add wifi firmware from vendor files
-#
-# Kernel config changes, based on: arch/arm/configs/janice_defconfig
-# - enable devtmpfs (needed for udev -> touch support in weston)
-# - disable ANDROID_PARANOID_NETWORK (removes network restrictions)
+# Kernel config based on: arch/arm/configs/janice_defconfig
 
-_vendor=samsung
-_flavor=samsung-i9070
-_hash="ac7219c4b8dcec7bc5a598d42c6be0db4aa36332"
-_config="config-${_flavor}.armhf"
-
-pkgname=linux-${_flavor}
+pkgname="linux-samsung-i9070"
 pkgver=3.0.101
-case $pkgver in
-	*.*.*)  _kernver=${pkgver%.*};;
-	*.*) _kernver=$pkgver;;
-esac
-pkgrel=9
-arch="armhf"
+pkgrel=10
 pkgdesc="Samsung Galaxy S Advance kernel from Epirex"
+arch="armhf"
+_carch="arm"
+_flavor="samsung-i9070"
 url="https://github.com/Epirex/Samsung_STE_Kernel"
-depends="postmarketos-mkinitfs"
-makedepends="perl sed installkernel bash gmp-dev bc linux-headers elfutils-dev busybox-static-armhf"
+license="GPL2"
 options="!strip !check !tracedeps"
-install=
+makedepends="perl sed installkernel bash gmp-dev bc linux-headers elfutils-dev busybox-static-armhf"
+HOSTCC="${CC:-gcc}"
+HOSTCC="${HOSTCC#${CROSS_COMPILE}}"
+
+# Source
+_repository="Samsung_STE_Kernel"
+_commit="ac7219c4b8dcec7bc5a598d42c6be0db4aa36332"
+_config="config-${_flavor}.armhf"
 source="
-	$pkgname-$_hash.tar.gz::https://github.com/Epirex/Samsung_STE_Kernel/archive/${_hash}.tar.gz
+	$pkgname-$_commit.tar.gz::https://github.com/Epirex/${_repository}/archive/${_commit}.tar.gz
 	$_config
 	00_fix_return_address.patch
 	01_remove_ramdisks_from_initramfs.patch
 	02_reduce_lzo_compression.patch
 	03_change_modules_install_dir.patch
 	04_change_dhd_firmware_dir.patch
+	05_fix_fb_rgb_mode.patch
 	compiler-gcc6.h
 	init
 "
-subpackages=""
-license="GPL2"
-
-_abi_release=${pkgver}
-_carch="arm"
-HOSTCC="${CC:-gcc}"
-HOSTCC="${HOSTCC#${CROSS_COMPILE}}"
-
-ksrcdir="$srcdir/Samsung_STE_Kernel-${_hash}"
+builddir="$srcdir/${_repository}-${_commit}"
 
 prepare() {
-	local _patch_failed=
-	cd "$ksrcdir"
-
-	# first apply patches in specified order
-	for i in $source; do
-		case $i in
-		*.patch)
-			msg "Applying $i..."
-			if ! patch -s -p1 -N -i "$srcdir"/$i; then
-				echo $i >>failed
-				_patch_failed=1
-			fi
-			;;
-		esac
-	done
-
-	if ! [ -z "$_patch_failed" ]; then
-		error "The following patches failed:"
-		cat failed
-		return 1
-	fi
+	default_prepare
 
 	# Use Alpine's busybox.static instead of the pre-compiled busybox shipped
 	# with the source
 	cp -v /usr/$(arch_to_hostspec $arch)/bin/busybox.static \
-		"$ksrcdir"/usr/u8500_initramfs_files/busybox
+		"$builddir"/usr/u8500_initramfs_files/busybox
 
 	# use custom init script in the initramfs which loads the initramfs from
 	# the kernel2 partition ("isorec")
-	cp -v "$srcdir"/init "$ksrcdir"/usr/u8500_initramfs_files/init
+	cp -v "$srcdir"/init "$builddir"/usr/u8500_initramfs_files/init
 
 	# gcc6 support
-	cp -v "$srcdir/compiler-gcc6.h" "$ksrcdir/include/linux/"
+	cp -v "$srcdir/compiler-gcc6.h" "$builddir/include/linux/"
 
-	mkdir -p "$srcdir"/build
-	cp "$srcdir"/$_config "$srcdir"/build/.config
-	make -C "$ksrcdir" O="$srcdir"/build ARCH="$_carch" HOSTCC="$HOSTCC" \
-		silentoldconfig
+	# Remove -Werror from all makefiles
+	find . -type f -name Makefile -print0 | \
+		xargs -0 sed -i 's/-Werror-/-W/g'
+	find . -type f -name Makefile -print0 | \
+		xargs -0 sed -i 's/-Werror//g'
+
+	cp "$srcdir"/$_config "$builddir"/.config
+	make ARCH="$_carch" HOSTCC="$HOSTCC" silentoldconfig
 }
 
-# this is so we can do: 'abuild menuconfig' to reconfigure kernel
 menuconfig() {
-	cd "$srcdir"/build
-	echo "--[ menuconfig ]--"
+	cd "$builddir"
 	make ARCH="$_carch" menuconfig
 	cp .config "$startdir"/$_config
 }
 
 build() {
-	cd "$srcdir"/build
 	unset LDFLAGS
-
-	echo "--[ Build kernel ]--"
 	make ARCH="$_carch" CC="${CC:-gcc}" \
-		KBUILD_BUILD_VERSION="$((pkgrel + 1))-Alpine"
-
-	echo "--[ Build modules ]--"
+		KBUILD_BUILD_VERSION="$((pkgrel + 1))-postmarketOS"
 	# the 'no-pic' flag is necessary to avoid the
 	# error 'Unknown symbol _GLOBAL_OFFSET_TABLE_ (err 0)' when loading the module
 	make ARCH="$_carch" CC="${CC:-gcc}" CFLAGS_MODULE="-fno-pic" \
-		KBUILD_BUILD_VERSION="$((pkgrel + 1))-Alpine" CONFIG_NO_ERROR_ON_MISMATCH=y \
-		modules
+		KBUILD_BUILD_VERSION="$((pkgrel + 1))-postmarketOS" modules
 }
 
 package() {
-	echo "--[ Installing kernel ]--"
-	install -Dm644 "$srcdir/build/arch/arm/boot/zImage" \
-		"$pkgdir/boot/vmlinuz-$_flavor"
-
-	install -D "$srcdir/build/include/config/kernel.release" \
+	# kernel.release
+	install -D "$builddir/include/config/kernel.release" \
 		"$pkgdir/usr/share/kernel/$_flavor/kernel.release"
 
-	cd "$srcdir"/build
-	unset LDFLAGS
+	# zImage (find the right one)
+	cd "$builddir/arch/$_carch/boot"
+	_target="$pkgdir/boot/vmlinuz-$_flavor"
+	for _zimg in zImage-dtb Image.gz-dtb *zImage Image; do
+		[ -e "$_zimg" ] || continue
+		msg "zImage found: $_zimg"
+		install -Dm644 "$_zimg" "$_target"
+		break
+	done
+	if ! [ -e "$_target" ]; then
+		error "Could not find zImage in $PWD!"
+		return 1
+	fi
 
-	echo "--[ Installing modules ]--"
+	# Modules
+	cd "$builddir"
+	unset LDFLAGS
 	make ARCH="$_carch" CC="${CC:-gcc}" \
-		KBUILD_BUILD_VERSION="$((pkgrel + 1))-Alpine" CONFIG_NO_ERROR_ON_MISMATCH=y \
-		INSTALL_MOD_PATH="$pkgdir" INSTALL_MOD_STRIP=1 modules_install
+		KBUILD_BUILD_VERSION="$((pkgrel + 1))-postmarketOS" \
+		INSTALL_MOD_PATH="$pkgdir" INSTALL_MOD_STRIP=1 \
+		modules_install
 }
 
 sha512sums="bb8218d803ec27f983449a43d14df75122311609a39e5b57095f4e8933752a2699fa0d4df1674aeee7d6e3a439551dacc9af3cab26b6e3e71f0441a4f16693df  linux-samsung-i9070-ac7219c4b8dcec7bc5a598d42c6be0db4aa36332.tar.gz
-84dab76407f10e1bc9072a53596a38d96acb129c67fbb8f8fe1c737e165ccaba283b1a20830c0ed6ec7a3183a85ccfee5f2918f99567f3bba8b3ffc01fc228e1  config-samsung-i9070.armhf
+63295d5ff1af86765ef35cc175f133be9ba29b9a4e0aac13e69af6dcca1952730db8b4444ca62ba47214ff0c5720aa126e95db0829396ba934d272fdbeb74fb5  config-samsung-i9070.armhf
 ea1d3b5a234fa565e3c1a792de48f4fc4e6023d281d303c8e319c7ef28edc5739ab0e4dea0139a41f0a5c7d03e27921ccaa214fd0ac5c72245a094ce60128864  00_fix_return_address.patch
-c8f12ecf578be0c4600563134079b980a1079b08ac868302af8821022befe873aa94c67b9690ba87f5967f0a48939d15e871dc2d2862bed7b6a1d0c9a95cfd8f  01_remove_ramdisks_from_initramfs.patch
+3c8e15644eced6f73c5c7d3df0437f3a9f750f4ec32d744c9e4266ccccef9e38316a898227a898a9fc0696bee0281c0e14312de2944e27a696f18a42deabb383  01_remove_ramdisks_from_initramfs.patch
 ef5b912c26fea4ab882592bdf7487942c64b123de8d25d08d976f29743f311742ee2f773bf2d110ddb5095f254dbb0bd4487c5cfce77311929082599199e7ebd  02_reduce_lzo_compression.patch
 27bba6d070db6f499d030680c020906fc3238dc60d90a9b2f0f3a355ef15beb227c1cf48b7858156264fe10f7943772ed00a837be36ba4b80de8199f0383e688  03_change_modules_install_dir.patch
 47533412cc91d2ead046039c90180ebc459e157017be85dca69cd882a183963448beb973f2cb7eaccbcd35354b0ed6a668131cd39ea30393dd52fd93b7e26815  04_change_dhd_firmware_dir.patch
+67278735e21c00d4208e76788d3d99ff1bd9c628608f60a73004f6deb8a4bc75fdf7c1e43108010c57aa6da06aa5e49292b109a2c4421212e181abaca45ea44d  05_fix_fb_rgb_mode.patch
 d80980e9474c82ba0ef1a6903b434d8bd1b092c40367ba543e72d2c119301c8b2d05265740e4104ca1ac5d15f6c4aa49e8776cb44264a9a28dc551e0d1850dcc  compiler-gcc6.h
 ef01c51c138239a49c1d00ae0074a07fed267d64934cf3d436a8ff057b91692ee2d040a45eacbb0dc62d5017a708c4dca2fadc282c850fa72aeebcfa787e2cbc  init"
