modem/msm-modem: uim-selection: Allow configuring wait time for SIM (MR 2695)
Unfortunately it looks like some modem firmwares (or SIM cards?) need
more time until the SIM card shows up in the modem. This means that the
SIM card might not get configured, making it look like it was not
detected at all. On the other hand, having the previous long wait loop
affects _all devices_ when there is really no SIM inserted.

The proper solution would be to make it possible to configure SIM cards
once they show up (probably in ModemManager). Until then, try to make it
possible to workaround this by introducing a configurable delay to wait
for the SIM card. It is set to minimal "1 seconds" by default but could
be increased by the user if needed to give the modem enough time to detect
the SIM card.

This reverts commit 683b543a3b65 ("msm-modem-uim-selection: Don't wait
for SIM (MR 2470)" but with a new configuration mechanism and a default
of 1 second only.

[ci:skip-build] already built successfully in CI

diff --git a/modem/msm-modem/msm-modem-uim-selection.initd b/modem/msm-modem/msm-modem-uim-selection.initd
--- a/modem/msm-modem/msm-modem-uim-selection.initd
+++ b/modem/msm-modem/msm-modem-uim-selection.initd
@@ -64,6 +64,22 @@ start() {
 
 	QMI_CARDS=$($QMICLI_MODEM --uim-get-card-status)
 
+	# Fail if all slots are empty but wait a bit for the sim to appear.
+	count=0
+	while ! printf "%s" "$QMI_CARDS" | grep -Fq "Card state: 'present'"
+	do
+		if [ "$count" -ge "$sim_wait_time" ]
+		then
+			eend 4 "No sim detected after $sim_wait_time seconds."
+			return 4
+		fi
+
+		sleep 1
+		count=$((count+1))
+		QMI_CARDS=$($QMICLI_MODEM --uim-get-card-status)
+	done
+	veinfo "Waited $count seconds for modem to come up"
+
 	# Clear the selected application in case the modem is in a bugged state
 	if ! printf "%s" "$QMI_CARDS" | grep -Fq "Primary GW:   session doesn't exist"
 	then
