[huawei-y530] Cleanup kernel APK, fix compilation issue, remove unnecessary DTBs (#872)

diff --git a/device/linux-huawei-y530/APKBUILD b/device/linux-huawei-y530/APKBUILD
--- a/device/linux-huawei-y530/APKBUILD
+++ b/device/linux-huawei-y530/APKBUILD
@@ -1,37 +1,25 @@
-# APKBUILD based on linux-vanilla aport. Changes:
-# - add !check !tracedeps
-# - add generation of master DTB with dtbTool
-#
 # Kernel config based on: arch/arm/configs/msm8610_defconfig
-# Changes:
-# - apply patches to compile with gcc6
-# - enable devtmpfs (needed for udev -> touch support in weston)
-# - disable input mouse driver
-# - enable generation of dtb
-# - disable ANDROID_PARANOID_NETWORK (removes network restrictions)
 
-_vendor=huawei
-_flavor=huawei-y530
-_config="config-${_flavor}.armhf"
-_repository="android_kernel_huawei_msm8x1x"
-_hash="1880463bf10c4c2d2b348698614a613902184e22"
-
-pkgname=linux-${_flavor}
+pkgname="linux-huawei-y530"
 pkgver=3.4.0
-case $pkgver in
-	*.*.*)  _kernver=${pkgver%.*};;
-	*.*) _kernver=$pkgver;;
-esac
-pkgrel=3
-arch="armhf"
+pkgrel=4
 pkgdesc="Kernel for Huawei MSM8x1x devices"
-url="https://github.com/PieroV/${_repository}"
-depends="postmarketos-mkinitfs"
-makedepends="perl sed installkernel bash gmp-dev bc linux-headers elfutils-dev dtbtool"
+arch="armhf"
+_carch="arm"
+_flavor="huawei-y530"
+url="https://github.com/PieroV/android_kernel_huawei_msm8x1x"
+license="GPL2"
 options="!strip !check !tracedeps"
-install=
+makedepends="perl sed installkernel bash gmp-dev bc linux-headers elfutils-dev dtbtool"
+HOSTCC="${CC:-gcc}"
+HOSTCC="${HOSTCC#${CROSS_COMPILE}}"
+
+# Source
+_repository="android_kernel_huawei_msm8x1x"
+_commit="1880463bf10c4c2d2b348698614a613902184e22"
+_config="config-${_flavor}.armhf"
 source="
-	$pkgname-$_hash.tar.gz::${url}/archive/${_hash}.tar.gz
+	$pkgname-$_commit.tar.gz::https://github.com/PieroV/${_repository}/archive/${_commit}.tar.gz
 	$_config
 	compiler-gcc6.h
 	00_fix_return_address.patch
@@ -43,98 +31,81 @@ source="
 	06_fix_mdss_fb_rgb_mode.patch
 	07_fix_mdss_fb_refresh_rate.patch
 	08_fix_touchscreen.patch
+	09_fix_various_include_directives.patch
 "
-subpackages=""
-license="GPL2"
-
-_abi_release=${pkgver}
-_carch="arm"
-HOSTCC="${CC:-gcc}"
-HOSTCC="${HOSTCC#${CROSS_COMPILE}}"
-
-ksrcdir="$srcdir/${_repository}-${_hash}"
+builddir="$srcdir/${_repository}-${_commit}"
 
 prepare() {
-	local _patch_failed=
-	cd "$ksrcdir"
-	make mrproper
-
-	# first apply patches in specified order
-	for i in $source; do
-		case $i in
-		*.patch)
-			msg "Applying $i..."
-			if ! patch -s -p1 -N -i "$srcdir"/$i; then
-				echo $i >>failed
-				_patch_failed=1
-			fi
-			;;
-		esac
-	done
-
-	if ! [ -z "$_patch_failed" ]; then
-		error "The following patches failed:"
-		cat failed
-		return 1
-	fi
+	default_prepare
 
 	# gcc6 support
-	cp -v "$srcdir/compiler-gcc6.h" "$ksrcdir/include/linux/"
+	cp -v "$srcdir/compiler-gcc6.h" "$builddir/include/linux/"
 
-	mkdir -p "$srcdir"/build
-	cp "$srcdir"/$_config "$srcdir"/build/.config
-	make -C "$ksrcdir" O="$srcdir"/build ARCH="$_carch" HOSTCC="$HOSTCC" \
-		silentoldconfig
+	# Remove -Werror from all makefiles
+	find . -type f -name Makefile -print0 | \
+		xargs -0 sed -i 's/-Werror-/-W/g'
+	find . -type f -name Makefile -print0 | \
+		xargs -0 sed -i 's/-Werror//g'
+
+	# Prepare kernel config ('yes ""' for kernels lacking olddefconfig)
+	cp "$srcdir"/$_config "$builddir"/.config
+	yes "" | make ARCH="$_carch" HOSTCC="$HOSTCC" oldconfig
 }
 
-
-
-# this is so we can do: 'abuild menuconfig' to reconfigure kernel
 menuconfig() {
-	cd "$srcdir"/build
-	echo "--[ menuconfig ]--"
+	cd "$builddir"
 	make ARCH="$_carch" menuconfig
 	cp .config "$startdir"/$_config
 }
 
 build() {
-	cd "$srcdir"/build
 	unset LDFLAGS
-
-	echo "--[ Build kernel ]--"
 	make ARCH="$_carch" CC="${CC:-gcc}" \
-		KBUILD_BUILD_VERSION="$((pkgrel + 1 ))-Alpine" CONFIG_NO_ERROR_ON_MISMATCH=y
+		CONFIG_NO_ERROR_ON_MISMATCH=y \
+		KBUILD_BUILD_VERSION="$((pkgrel + 1 ))-postmarketOS"
 
-	echo "--[ Build modules ]--"
 	# the 'no-pic' flag is necessary to avoid the
 	# error 'Unknown symbol _GLOBAL_OFFSET_TABLE_ (err 0)' when loading the module
 	make ARCH="$_carch" CC="${CC:-gcc}" CFLAGS_MODULE="-fno-pic" \
-		KBUILD_BUILD_VERSION="$((pkgrel + 1))-Alpine" CONFIG_NO_ERROR_ON_MISMATCH=y \
+		CONFIG_NO_ERROR_ON_MISMATCH=y \
+		KBUILD_BUILD_VERSION="$((pkgrel + 1))-postmarketOS" \
 		modules
 
-	echo "--[ Generate master DTB ]--"
+	# Generate master DTB
 	dtbTool -s 2048 -p "scripts/dtc/" -o "arch/arm/boot/dt.img" "arch/arm/boot/"
 }
 
 package() {
-	echo "--[ Installing kernel ]--"
-	install -Dm644 "$srcdir/build/arch/arm/boot/zImage" \
-		"$pkgdir/boot/vmlinuz-$_flavor"
-
-	echo "--[ Installing master DTB ]--"
-	install -Dm644 "$srcdir/build/arch/arm/boot/dt.img" \
-		"$pkgdir/boot/dt.img"
-
-	install -D "$srcdir/build/include/config/kernel.release" \
+	# kernel.release
+	install -D "$builddir/include/config/kernel.release" \
 		"$pkgdir/usr/share/kernel/$_flavor/kernel.release"
 
-	cd "$srcdir"/build
-	unset LDFLAGS
+	# zImage (find the right one)
+	cd "$builddir/arch/$_carch/boot"
+	_target="$pkgdir/boot/vmlinuz-$_flavor"
+	for _zimg in zImage-dtb Image.gz-dtb *zImage Image; do
+		[ -e "$_zimg" ] || continue
+		msg "zImage found: $_zimg"
+		install -Dm644 "$_zimg" "$_target"
+		break
+	done
+	if ! [ -e "$_target" ]; then
+		error "Could not find zImage in $PWD!"
+		return 1
+	fi
 
-	echo "--[ Installing modules ]--"
+	# Master DTB
+	install -Dm644 "$builddir/arch/arm/boot/dt.img" \
+		"$pkgdir/boot/dt.img"
+
+	# Modules
+	cd "$builddir"
+	unset LDFLAGS
 	make ARCH="$_carch" CC="${CC:-gcc}" \
-		KBUILD_BUILD_VERSION="$((pkgrel + 1))-Alpine" CONFIG_NO_ERROR_ON_MISMATCH=y \
-		INSTALL_MOD_PATH="$pkgdir" INSTALL_MOD_STRIP=1 modules_install
+		CONFIG_NO_ERROR_ON_MISMATCH=y \
+		KBUILD_BUILD_VERSION="$((pkgrel + 1))-postmarketOS" \
+		INSTALL_MOD_PATH="$pkgdir" INSTALL_MOD_STRIP=1 \
+		modules_install
 }
 
 sha512sums="b88fe4981fb35d289977c9a7ca6b041ec8d09380250485d7b3f3e1e1ef51ba500db2e1aecd222aa8c140a3b9ec5ed2fa638b68ddf446efe81f278aa8b8e7871f  linux-huawei-y530-1880463bf10c4c2d2b348698614a613902184e22.tar.gz
@@ -144,8 +115,9 @@ ea1d3b5a234fa565e3c1a792de48f4fc4e6023d281d303c8e319c7ef28edc5739ab0e4dea0139a41
 a2bb98fb8d988bbb659cae00fbaca360828300e9b98b90aed5ee0dd839c3f740696df4094a9021b813cbada06820d115aabed581a47cdd2c947e8d853c20b145  01_timeconst_fix.patch
 7be03a9e78b7ac330a54b1f00509caa0621a95c0c55901878ad757f9dd69cc05ba2c8b5ea987063ae1224f92c4d090d515fa5d369e7755181a4871b0d0f82881  02_gpu-msm-fix-gcc5-compile.patch
 760fdff79df31754ebed59839f34fc8c5a61750471614ac93a01b1e13b2535e7ca1f879c0cad3e83ad92946586c91679ba853eac4fe454d7e948317c84d81941  03_avoid_rpmb_read_during_boot.patch
-42716cf894445fe02a46a1f26b2faa4d45ffea35e2dfc15acf5ce66fdd67d5faf8201b07ea10716c61c7f900561262731771c7b655f9e95ff7a9273de5746244  04_add_missing_dtb.patch
+e1fff84343ec4374a7c4bd9e472fc1c7b1b00efc059724b16ca0b7980b7ff55e542310a3bfbf12a0a1b7936261fee8e633d43be1a084ff3ba64e5e8d271a51f0  04_add_missing_dtb.patch
 fbc61e379403990167853f4c4fbdfa22d7e9661a7eedecf2a75eec2a8008991a82d0a61be844ab4b1c88383f3fa79b43eff10b1039e44ad5a758a173cbf6386b  05_fix_mdp3_ctrl_off.patch
 384ae0bf2f5d7e15b0b60655693fd600b52c0f5bfcaa4ba7336d0ebeb224e84b99b597f77d26a1249e14a4e7bbc1629be00556b393bb9dd2266cb4bd67c3cfea  06_fix_mdss_fb_rgb_mode.patch
 1f743d3e7f4ac7401167ea35edc7d7e113bd80824c4d53631d7500f33557ff486163f8244786c16506b2e21db6ccbcd8a0f7b26fcf4937efee50b62c074f9a22  07_fix_mdss_fb_refresh_rate.patch
-f83e9b6549155a2f32c89dffbab3ad6fba7b8d93976dfccb1232833244ed6e064e28105a321eaa934c5bb326384730d03f3d3141227a7258a30045fa12573268  08_fix_touchscreen.patch"
+f83e9b6549155a2f32c89dffbab3ad6fba7b8d93976dfccb1232833244ed6e064e28105a321eaa934c5bb326384730d03f3d3141227a7258a30045fa12573268  08_fix_touchscreen.patch
+c9831aa037d4cb26fa349c44a27111daf8f7a84a9527d0221ecc4f01839b195243c178838663ff7592bb1d5c3cdc9872b449254beb7b9dffa67c365c3d8e042c  09_fix_various_include_directives.patch"
