recovery zip: support twrp.fstab filename in addition to recovery.fstab (fix for compatibility with TWRP on sony-yuga)

diff --git a/main/postmarketos-android-recovery-installer/pmos_chroot b/main/postmarketos-android-recovery-installer/pmos_chroot
--- a/main/postmarketos-android-recovery-installer/pmos_chroot
+++ b/main/postmarketos-android-recovery-installer/pmos_chroot
@@ -28,9 +28,18 @@ done
 mount --bind /tmp/postmarketos/pmos.log "$CHROOT"/pmos.log
 mount --bind "$ZIP" "$CHROOT"/pmos.zip
 
+fstab_recovery="recovery.fstab"
+# TWRP can use twrp.fstab instead of recovery.fstab (device specific)
+# This check exists to support both formats.
+if [ ! -e "/etc/"$fstab_recovery ]; then
+	fstab_recovery="twrp.fstab"
+fi
+
 # Create copy of fstab file provided by the recovery
-cp /etc/recovery.fstab "$CHROOT"/recovery.fstab || {
-	[ "$?" = '255' ] && echo 'recovery.fstab not found, continuing...' || exit "$?" ; }
+if ! cp /etc/$fstab_recovery "$CHROOT"/$fstab_recovery; then
+	echo "Error copying $fstab_recovery , exiting..."
+	exit 1
+fi
 
 # Mount necessary filesystems for the chroot
 for mountpoint in "/dev" "/proc" "/sys"
